[project]
name = "p4print"
version = "0.2.1"
description = "Use 'p()' instead of 'print()' in Python"
readme = "README.md"  # This must match an existing file in your directory
requires-python = ">=3.0"
dependencies = []
