[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "p4print"  # ✅ Change from lazyprint to p4print
version = "0.2.1"  # Increment the version
description = "A simple package to use 'p()' instead of 'print()'"
